version: '2.1'

services:
  database:
    extends:
      file: mysql.yml
      service: mysql${MYSQL:-5.5}
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: oro_db
      MYSQL_USER: oro_db_user
      MYSQL_PASSWORD: oro_db_pass
    ports:
      - "3306"
    expose:
      - "3306"

  mysql5.5:
    image: oroinc/mysql:${PATCH:-5.5}

  mysql5.6:
    image: oroinc/mysql:${PATCH:-5.6}
